"""init schema

Revision ID: 8c3183eccb71
Revises: 
Create Date: 2025-10-04 14:13:56.827211

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '8c3183eccb71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spt_fallback_dev')
    op.drop_table('spt_fallback_usg')
    op.drop_table('MSreplication_options')
    op.drop_table('spt_fallback_db')
    op.drop_table('spt_monitor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spt_monitor',
    sa.Column('lastrun', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('cpu_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('io_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_read', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_write', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_errors', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_db',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_dbid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False)
    )
    op.create_table('MSreplication_options',
    sa.Column('optname', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('value', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('major_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minor_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('install_failures', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_usg',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_vstart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('segmap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lstart', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sizepg', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vstart', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_dev',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xfallback_drive', sa.CHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('high', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phyname', sa.VARCHAR(length=127, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False)
    )
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
