name: Deploy Backend & Frontend to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set version tags using commit SHA
      - name: Set image tags
        id: vars
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/backend:$COMMIT_SHA" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/frontend:$COMMIT_SHA" >> $GITHUB_ENV

      # 3️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4️⃣ Build & push Backend image
      - name: Build & push Backend image
        run: |
          docker build -t $BACKEND_IMAGE ./backend
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push $BACKEND_IMAGE

      # 5️⃣ Build & push Frontend image
      - name: Build & push Frontend image
        run: |
          docker build -t $FRONTEND_IMAGE ./frontend
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push $FRONTEND_IMAGE

      # 6️⃣ Deploy Backend ACA
      - name: Deploy Backend ACA
        run: |
          az containerapp update \
            --name backend-api \
            --resource-group ${{ secrets.AZURE_RG }} \
            --image $BACKEND_IMAGE

      # 7️⃣ Deploy Frontend ACA
      - name: Deploy Frontend ACA
        run: |
          az containerapp update \
            --name frontend-app \
            --resource-group ${{ secrets.AZURE_RG }} \
            --image $FRONTEND_IMAGE
