name: Build & Push Docker Images to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Login to Azure Container Registry
      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # 4️⃣ Set Image Tags
      - name: Set image tags
        id: vars
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "BACKEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/backend:$COMMIT_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_LATEST=${{ secrets.ACR_NAME }}.azurecr.io/backend:latest" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/frontend:$COMMIT_SHA" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_LATEST=${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest" >> $GITHUB_ENV

      # 5️⃣ Build & Push Backend Image
      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE -t $BACKEND_IMAGE_LATEST ./backend
          docker push $BACKEND_IMAGE
          docker push $BACKEND_IMAGE_LATEST

      # 6️⃣ Build & Push Frontend Image
      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE -t $FRONTEND_IMAGE_LATEST ./frontend
          docker push $FRONTEND_IMAGE
          docker push $FRONTEND_IMAGE_LATEST
