name: Deploy Backend & Frontend to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ ACR Docker login via Azure CLI
      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # 4️⃣ Set Image Tags
      - name: Set image tags
        id: vars
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "BACKEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/backend:$COMMIT_SHA" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/frontend:$COMMIT_SHA" >> $GITHUB_ENV

      # 5️⃣ Build & Push Backend Image
      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE ./backend
          docker push $BACKEND_IMAGE

      # 6️⃣ Deploy Backend to Azure Container Apps
      - name: Deploy Backend ACA
        uses: azure/container-apps-deploy@v0
        with:
          containerAppName: backend-api
          resourceGroup: ${{ secrets.AZURE_RG }}
          image: ${{ env.BACKEND_IMAGE }}

      # 7️⃣ Build & Push Frontend Image
      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMAGE ./frontend
          docker push $FRONTEND_IMAGE

      # 8️⃣ Deploy Frontend to Azure Container Apps
      - name: Deploy Frontend ACA
        uses: azure/container-apps-deploy@v0
        with:
          containerAppName: frontend-app
          resourceGroup: ${{ secrets.AZURE_RG }}
          image: ${{ env.FRONTEND_IMAGE }}
