name: Build, Push & Deploy Backend to ACR + ACI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Docker Login to ACR
      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
#
#      # 4️⃣ Set backend image tags
#      - name: Set image tags
#        id: vars
#        run: |
#          COMMIT_SHA=$(git rev-parse --short HEAD)
#          echo "BACKEND_IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/backend:$COMMIT_SHA" >> $GITHUB_ENV
#          echo "BACKEND_IMAGE_LATEST=${{ secrets.ACR_NAME }}.azurecr.io/backend:latest" >> $GITHUB_ENV
#
#      # 5️⃣ Build & Push Backend Image
#      - name: Build & Push Backend Image
#        run: |
#          docker build -t $BACKEND_IMAGE -t $BACKEND_IMAGE_LATEST ./backend
#          docker push $BACKEND_IMAGE
#          docker push $BACKEND_IMAGE_LATEST


 # 6️⃣ Update existing Container App
      - name: Update Container App
        env:
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        run: |
          CONTAINER_APP_NAME=inventory-backend
          CONTAINER_APP_ENV=inventory-container-env

          echo "Updating Container App '$CONTAINER_APP_NAME' with new image..."
          az containerapp update \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --image "$BACKEND_IMAGE_LATEST"